Package Project2;

Helpers
            digit = ['0'..'9'];
            lf = 10; 
            sp = ' '; 
			period = '.';
Tokens
			class = 'class';
			public = 'public';
			static = 'static';
			void = 'void';
			main = 'main';
			string = 'String';
			lcurly = '{';
			rcurly = '}';
			lbracket = '[';
			rbracket = ']';
			lparen = '(';
			rparen = ')';
			extends = 'extends';
			semicolon = ';';
			return = 'return';
			int = 'int';
			bool = 'boolean';
            if = 'if';
			else = 'else';
			while = 'while';
			print = 'System.out.println';
			equal = '=';
			and = '&&';
			lt = '<';
			plus = '+';
			minus = '-';
			times = '*';
			period = period;
			length = 'length';
			comma = ',';
			true = 'true';
			false = 'false';
			this = 'this';
			new = 'new';
			exc = '!';
			blank = ( sp | 13 | lf| 9)+;
			comments = '//' [[0 .. 0xffff]- [13 + 10]]* | '/*' [[0 .. 0xffff] - ['*' + '/']]* '*/';
			real = ((digit)+ period (digit)*);
			number = (digit)+;
			id = ((['a'..'z'] | ['A'..'Z'])(digit | (['a'..'z'] | ['A'..'Z']) | '_')*);
Ignored Tokens
			blank;
