/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.node;

import Project3.analysis.*;

@SuppressWarnings("nls")
public final class TPrint extends Token
{
    public TPrint()
    {
        super.setText("echo");
    }

    public TPrint(int line, int pos)
    {
        super.setText("echo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrint(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrint(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrint text.");
    }
}
