/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project3.analysis;

import Project3.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPrint(TPrint node);
    void caseTClass(TClass node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTMain(TMain node);
    void caseTString(TString node);
    void caseTLcurly(TLcurly node);
    void caseTRcurly(TRcurly node);
    void caseTLbracket(TLbracket node);
    void caseTRbracket(TRbracket node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTExtends(TExtends node);
    void caseTSemicolon(TSemicolon node);
    void caseTReturn(TReturn node);
    void caseTInt(TInt node);
    void caseTBool(TBool node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTEqual(TEqual node);
    void caseTAnd(TAnd node);
    void caseTLt(TLt node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTTimes(TTimes node);
    void caseTPeriod(TPeriod node);
    void caseTLength(TLength node);
    void caseTComma(TComma node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTThis(TThis node);
    void caseTNew(TNew node);
    void caseTExc(TExc node);
    void caseTBlank(TBlank node);
    void caseTComments(TComments node);
    void caseTReal(TReal node);
    void caseTNumber(TNumber node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
