/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AIncrForIncrStep extends PForIncrStep
{
    private TId _id_;
    private TIncr _incr_;

    public AIncrForIncrStep()
    {
        // Constructor
    }

    public AIncrForIncrStep(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TIncr _incr_)
    {
        // Constructor
        setId(_id_);

        setIncr(_incr_);

    }

    @Override
    public Object clone()
    {
        return new AIncrForIncrStep(
            cloneNode(this._id_),
            cloneNode(this._incr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIncrForIncrStep(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TIncr getIncr()
    {
        return this._incr_;
    }

    public void setIncr(TIncr node)
    {
        if(this._incr_ != null)
        {
            this._incr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._incr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._incr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._incr_ == child)
        {
            this._incr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._incr_ == oldChild)
        {
            setIncr((TIncr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
