/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMethodCallInClassStmt extends PStmt
{
    private TId _firstId_;
    private PArrayOption _arrayOption_;
    private TPeriod _period_;
    private TId _instanceId_;
    private TLparen _lparen_;
    private PVarListTwo _varListTwo_;
    private TRparen _rparen_;
    private PMethodChainingOption _methodChainingOption_;
    private TSemicolon _semicolon_;

    public AMethodCallInClassStmt()
    {
        // Constructor
    }

    public AMethodCallInClassStmt(
        @SuppressWarnings("hiding") TId _firstId_,
        @SuppressWarnings("hiding") PArrayOption _arrayOption_,
        @SuppressWarnings("hiding") TPeriod _period_,
        @SuppressWarnings("hiding") TId _instanceId_,
        @SuppressWarnings("hiding") TLparen _lparen_,
        @SuppressWarnings("hiding") PVarListTwo _varListTwo_,
        @SuppressWarnings("hiding") TRparen _rparen_,
        @SuppressWarnings("hiding") PMethodChainingOption _methodChainingOption_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setFirstId(_firstId_);

        setArrayOption(_arrayOption_);

        setPeriod(_period_);

        setInstanceId(_instanceId_);

        setLparen(_lparen_);

        setVarListTwo(_varListTwo_);

        setRparen(_rparen_);

        setMethodChainingOption(_methodChainingOption_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AMethodCallInClassStmt(
            cloneNode(this._firstId_),
            cloneNode(this._arrayOption_),
            cloneNode(this._period_),
            cloneNode(this._instanceId_),
            cloneNode(this._lparen_),
            cloneNode(this._varListTwo_),
            cloneNode(this._rparen_),
            cloneNode(this._methodChainingOption_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodCallInClassStmt(this);
    }

    public TId getFirstId()
    {
        return this._firstId_;
    }

    public void setFirstId(TId node)
    {
        if(this._firstId_ != null)
        {
            this._firstId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._firstId_ = node;
    }

    public PArrayOption getArrayOption()
    {
        return this._arrayOption_;
    }

    public void setArrayOption(PArrayOption node)
    {
        if(this._arrayOption_ != null)
        {
            this._arrayOption_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayOption_ = node;
    }

    public TPeriod getPeriod()
    {
        return this._period_;
    }

    public void setPeriod(TPeriod node)
    {
        if(this._period_ != null)
        {
            this._period_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._period_ = node;
    }

    public TId getInstanceId()
    {
        return this._instanceId_;
    }

    public void setInstanceId(TId node)
    {
        if(this._instanceId_ != null)
        {
            this._instanceId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instanceId_ = node;
    }

    public TLparen getLparen()
    {
        return this._lparen_;
    }

    public void setLparen(TLparen node)
    {
        if(this._lparen_ != null)
        {
            this._lparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lparen_ = node;
    }

    public PVarListTwo getVarListTwo()
    {
        return this._varListTwo_;
    }

    public void setVarListTwo(PVarListTwo node)
    {
        if(this._varListTwo_ != null)
        {
            this._varListTwo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varListTwo_ = node;
    }

    public TRparen getRparen()
    {
        return this._rparen_;
    }

    public void setRparen(TRparen node)
    {
        if(this._rparen_ != null)
        {
            this._rparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rparen_ = node;
    }

    public PMethodChainingOption getMethodChainingOption()
    {
        return this._methodChainingOption_;
    }

    public void setMethodChainingOption(PMethodChainingOption node)
    {
        if(this._methodChainingOption_ != null)
        {
            this._methodChainingOption_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodChainingOption_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._firstId_)
            + toString(this._arrayOption_)
            + toString(this._period_)
            + toString(this._instanceId_)
            + toString(this._lparen_)
            + toString(this._varListTwo_)
            + toString(this._rparen_)
            + toString(this._methodChainingOption_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._firstId_ == child)
        {
            this._firstId_ = null;
            return;
        }

        if(this._arrayOption_ == child)
        {
            this._arrayOption_ = null;
            return;
        }

        if(this._period_ == child)
        {
            this._period_ = null;
            return;
        }

        if(this._instanceId_ == child)
        {
            this._instanceId_ = null;
            return;
        }

        if(this._lparen_ == child)
        {
            this._lparen_ = null;
            return;
        }

        if(this._varListTwo_ == child)
        {
            this._varListTwo_ = null;
            return;
        }

        if(this._rparen_ == child)
        {
            this._rparen_ = null;
            return;
        }

        if(this._methodChainingOption_ == child)
        {
            this._methodChainingOption_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._firstId_ == oldChild)
        {
            setFirstId((TId) newChild);
            return;
        }

        if(this._arrayOption_ == oldChild)
        {
            setArrayOption((PArrayOption) newChild);
            return;
        }

        if(this._period_ == oldChild)
        {
            setPeriod((TPeriod) newChild);
            return;
        }

        if(this._instanceId_ == oldChild)
        {
            setInstanceId((TId) newChild);
            return;
        }

        if(this._lparen_ == oldChild)
        {
            setLparen((TLparen) newChild);
            return;
        }

        if(this._varListTwo_ == oldChild)
        {
            setVarListTwo((PVarListTwo) newChild);
            return;
        }

        if(this._rparen_ == oldChild)
        {
            setRparen((TRparen) newChild);
            return;
        }

        if(this._methodChainingOption_ == oldChild)
        {
            setMethodChainingOption((PMethodChainingOption) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
