/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMoreVarListTwo extends PMoreVarListTwo
{
    private TComma _comma_;
    private PVarListTwo _varListTwo_;

    public AMoreVarListTwo()
    {
        // Constructor
    }

    public AMoreVarListTwo(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PVarListTwo _varListTwo_)
    {
        // Constructor
        setComma(_comma_);

        setVarListTwo(_varListTwo_);

    }

    @Override
    public Object clone()
    {
        return new AMoreVarListTwo(
            cloneNode(this._comma_),
            cloneNode(this._varListTwo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreVarListTwo(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PVarListTwo getVarListTwo()
    {
        return this._varListTwo_;
    }

    public void setVarListTwo(PVarListTwo node)
    {
        if(this._varListTwo_ != null)
        {
            this._varListTwo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varListTwo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._varListTwo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._varListTwo_ == child)
        {
            this._varListTwo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._varListTwo_ == oldChild)
        {
            setVarListTwo((PVarListTwo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
