/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMoreIdsVarlist extends PVarlist
{
    private TId _id_;
    private TColon _colon_;
    private PType _type_;
    private PArrayOption _arrayOption_;
    private PMoreVarlist _moreVarlist_;

    public AMoreIdsVarlist()
    {
        // Constructor
    }

    public AMoreIdsVarlist(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") PArrayOption _arrayOption_,
        @SuppressWarnings("hiding") PMoreVarlist _moreVarlist_)
    {
        // Constructor
        setId(_id_);

        setColon(_colon_);

        setType(_type_);

        setArrayOption(_arrayOption_);

        setMoreVarlist(_moreVarlist_);

    }

    @Override
    public Object clone()
    {
        return new AMoreIdsVarlist(
            cloneNode(this._id_),
            cloneNode(this._colon_),
            cloneNode(this._type_),
            cloneNode(this._arrayOption_),
            cloneNode(this._moreVarlist_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreIdsVarlist(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PArrayOption getArrayOption()
    {
        return this._arrayOption_;
    }

    public void setArrayOption(PArrayOption node)
    {
        if(this._arrayOption_ != null)
        {
            this._arrayOption_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayOption_ = node;
    }

    public PMoreVarlist getMoreVarlist()
    {
        return this._moreVarlist_;
    }

    public void setMoreVarlist(PMoreVarlist node)
    {
        if(this._moreVarlist_ != null)
        {
            this._moreVarlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moreVarlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._colon_)
            + toString(this._type_)
            + toString(this._arrayOption_)
            + toString(this._moreVarlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._arrayOption_ == child)
        {
            this._arrayOption_ = null;
            return;
        }

        if(this._moreVarlist_ == child)
        {
            this._moreVarlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._arrayOption_ == oldChild)
        {
            setArrayOption((PArrayOption) newChild);
            return;
        }

        if(this._moreVarlist_ == oldChild)
        {
            setMoreVarlist((PMoreVarlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
