/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMoreIdsMoreIds extends PMoreIds
{
    private TComma _comma_;
    private TId _id_;
    private PMoreIds _moreIds_;

    public AMoreIdsMoreIds()
    {
        // Constructor
    }

    public AMoreIdsMoreIds(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PMoreIds _moreIds_)
    {
        // Constructor
        setComma(_comma_);

        setId(_id_);

        setMoreIds(_moreIds_);

    }

    @Override
    public Object clone()
    {
        return new AMoreIdsMoreIds(
            cloneNode(this._comma_),
            cloneNode(this._id_),
            cloneNode(this._moreIds_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreIdsMoreIds(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PMoreIds getMoreIds()
    {
        return this._moreIds_;
    }

    public void setMoreIds(PMoreIds node)
    {
        if(this._moreIds_ != null)
        {
            this._moreIds_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moreIds_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._id_)
            + toString(this._moreIds_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._moreIds_ == child)
        {
            this._moreIds_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._moreIds_ == oldChild)
        {
            setMoreIds((PMoreIds) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
