/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class AMoreIdsMoreVarlist extends PMoreVarlist
{
    private TComma _comma_;
    private PVarlist _varlist_;

    public AMoreIdsMoreVarlist()
    {
        // Constructor
    }

    public AMoreIdsMoreVarlist(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PVarlist _varlist_)
    {
        // Constructor
        setComma(_comma_);

        setVarlist(_varlist_);

    }

    @Override
    public Object clone()
    {
        return new AMoreIdsMoreVarlist(
            cloneNode(this._comma_),
            cloneNode(this._varlist_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreIdsMoreVarlist(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PVarlist getVarlist()
    {
        return this._varlist_;
    }

    public void setVarlist(PVarlist node)
    {
        if(this._varlist_ != null)
        {
            this._varlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._varlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._varlist_ == child)
        {
            this._varlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._varlist_ == oldChild)
        {
            setVarlist((PVarlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
