/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ANegativeFactor extends PFactor
{
    private TNegop _negop_;
    private PFactor _factor_;

    public ANegativeFactor()
    {
        // Constructor
    }

    public ANegativeFactor(
        @SuppressWarnings("hiding") TNegop _negop_,
        @SuppressWarnings("hiding") PFactor _factor_)
    {
        // Constructor
        setNegop(_negop_);

        setFactor(_factor_);

    }

    @Override
    public Object clone()
    {
        return new ANegativeFactor(
            cloneNode(this._negop_),
            cloneNode(this._factor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativeFactor(this);
    }

    public TNegop getNegop()
    {
        return this._negop_;
    }

    public void setNegop(TNegop node)
    {
        if(this._negop_ != null)
        {
            this._negop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negop_ = node;
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negop_)
            + toString(this._factor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negop_ == child)
        {
            this._negop_ = null;
            return;
        }

        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negop_ == oldChild)
        {
            setNegop((TNegop) newChild);
            return;
        }

        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
