/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class APlusAddop extends PAddop
{
    private TPlusop _plusop_;

    public APlusAddop()
    {
        // Constructor
    }

    public APlusAddop(
        @SuppressWarnings("hiding") TPlusop _plusop_)
    {
        // Constructor
        setPlusop(_plusop_);

    }

    @Override
    public Object clone()
    {
        return new APlusAddop(
            cloneNode(this._plusop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAddop(this);
    }

    public TPlusop getPlusop()
    {
        return this._plusop_;
    }

    public void setPlusop(TPlusop node)
    {
        if(this._plusop_ != null)
        {
            this._plusop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusop_ == child)
        {
            this._plusop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusop_ == oldChild)
        {
            setPlusop((TPlusop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
