/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class ATypesType extends PType
{
    private TTypeDecl _typeDecl_;

    public ATypesType()
    {
        // Constructor
    }

    public ATypesType(
        @SuppressWarnings("hiding") TTypeDecl _typeDecl_)
    {
        // Constructor
        setTypeDecl(_typeDecl_);

    }

    @Override
    public Object clone()
    {
        return new ATypesType(
            cloneNode(this._typeDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypesType(this);
    }

    public TTypeDecl getTypeDecl()
    {
        return this._typeDecl_;
    }

    public void setTypeDecl(TTypeDecl node)
    {
        if(this._typeDecl_ != null)
        {
            this._typeDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDecl_ == child)
        {
            this._typeDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeDecl_ == oldChild)
        {
            setTypeDecl((TTypeDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
