/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project5.node;

import Project5.analysis.*;

@SuppressWarnings("nls")
public final class TClassLit extends Token
{
    public TClassLit()
    {
        super.setText("CLASS");
    }

    public TClassLit(int line, int pos)
    {
        super.setText("CLASS");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TClassLit(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClassLit(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TClassLit text.");
    }
}
